### ISSUE TITLE
Arrow support

### ISSUE THREAD

**Issue by domoritz** [omnisci/mapd-connector#108]
When loading larger datasets with the MapD connector, there is a large deserialization overhead. MapD already supports arrow, which would dramatically reduce this overhead, but it is not available from the connector. It would be great if the connector supported accessing arrow files.

**Comment by tmostak** [comment]
Yes, that would be amazing. Wish I could upvote In Github issues.

**Comment by domoritz** [comment]
Apache arrow js 0.4 was just released. It would be great to have arrow support in the connector. On the Vega side, we are working on arrow support now but it would be best if we could build a demo on top of OmniSci.

**Comment by domoritz** [comment]
Vega now has an arrow loader: https://github.com/vega/vega-loader-arrow.
