### ISSUE TITLE
npm ERR! 404  '@mapd/connector@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by sandipp** [omnisci/mapd-connector#144]
## :beetle: If bug
  - [ ] Operating System and version: macOS 10.14.4 (18E226)
  - [ ] Browser and version: Chrome (Version 73.0.3683.103 (Official Build) (64-bit))
  - [ ] Steps to reproduce (including dashboard link): `npm info @mapd/connector` or `npm install @mapd/connector`
  - [ ] Description of issue: `npm install` and `npm info` is failing with the following error-

```
 $ npm info @mapd/connector
npm ERR! code E404
npm ERR! 404 '@mapd/connector' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  '@mapd/connector@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by int3h** [comment]
Sorry for the long wait for a reply, @sandipp . I am not able to replicate this locally. Are you still experiencing this problem?

**Comment by jrajav** [comment]
I'm also unable to replicate, with the same command. Please re-open if you encounter this issue again, though!
