### ISSUE TITLE
Handle undefined `row_desc` in `getFields` Method

### ISSUE THREAD

**Issue by mrblueblue** [omnisci/mapd-connector#15]
In the `getField` method, we create a row dictionary in a way that can cause a runtime error when the return `fields` object has an undefined `row_desc` key

```js
const rowDict = fields.row_desc.reduce((accum, value) => {
  accum[value.col_name] = value
    return accum
}, {})
```

**Comment by Davidiskander** [comment]
Still the same as of V3.2.3
