### ISSUE TITLE
Cannot connect to metis / demo is broken

### ISSUE THREAD

**Issue by domoritz** [omnisci/mapd-connector#162]
https://omnisci.github.io/mapd-connector/examples/browser.html

![Screen Shot 2019-08-30 at 1 19 56 PM](https://user-images.githubusercontent.com/589034/64049216-f4574080-cb28-11e9-87f3-1b0344fd6561.png)

**Comment by niviksha** [comment]
thanks @domoritz  - looking

**Comment by jrajav** [comment]
@domoritz This was a temporary environmental glitch - we think it's resolved now, can you please verify?

**Comment by pantosik** [comment]
updated to 4.8.1 and cuda updated to 418.87.  Machine up and demo running.

**Comment by domoritz** [comment]
Thank you for the super fast response. Everything is working again. 🤗
