### ISSUE TITLE
Demo instance throws "License invalid" error

### ISSUE THREAD

**Issue by domoritz** [omnisci/mapd-connector#189]
It looks like a license on the demo instance at `metis.mapd.com`. A lot of demos on the internet rely on the test instance. For example, all of these are broken right now: https://observablehq.com/search?query=mapd. Could you update the license on the demo instance?

Also see https://github.com/vega/scalable-vega/issues/54.

**Comment by jrajav** [comment]
@domoritz Thanks for the heads up. We're looking into it

**Comment by jrajav** [comment]
@domoritz Should be fixed now. Mind double-checking?

**Comment by domoritz** [comment]
Works for me. Thank you for fixing the issue quickly and setting up scripts to renew the license automatically.
