### ISSUE TITLE
Integrate Tests as Part of Automatic Thrift Updates 

### ISSUE THREAD

**Issue by mrblueblue** [omnisci/mapd-connector#19]
Currently, our thrift files are automatically updated and those changes are automatically made into a pull request against the `develop` branch.

The missing part of this process is running the PR against automated tests.

I am proposing that we integrate some sort of automated unit and integration testing with this process so that all thrift update PR's are verifiably non-breaking.

**Comment by jrajav** [comment]
Outdated with current manual process - closing for now.
