### ISSUE TITLE
Arrow library is not externalized

### ISSUE THREAD

**Issue by domoritz** [omnisci/mapd-connector#213]
:beetle:

In 5.5.1, the arrow library is not externalized in the compiled bundle. That means that if someone wants to check whether the dataframe is an instance of an arrow dataframe, they cannot easily do it. the problem is that the constructors are not the same (the connector has their own version of arrow, not the same that someone else might use to check the type).

Because of this issue, the check in https://github.com/vega/vega-loader-arrow/blob/36e1d0d2b0050f6e207327e78367007c4d25e28b/src/arrow.js#L20 does not work.

**Comment by israelvicars** [comment]
@jclay Do we need to approach this with dual support so that a default case can be overridden by all? Noticing the build failure in https://github.com/omnisci/mapd-connector/pull/214
