### ISSUE TITLE
Use Promise for all async interface methods

### ISSUE THREAD

**Issue by jrajav** [omnisci/mapd-connector#59]
<img width="739" alt="screen shot 2018-02-15 at 10 22 20" src="https://user-images.githubusercontent.com/2074135/36271278-c9b62890-1243-11e8-8ca4-2a237f1d0bf3.png">

^ This shouldn't be necessary.

**Comment by micahstubbs** [comment]
source https://beta.observablehq.com/@mbostock/hello-mapd-connector

**Comment by jrajav** [comment]
This is already done in that Promise-based async methods are available and used for all mapd-connector usages throughout first-party code (Immerse, mapd-charting, and mapd-crossfilter). All that remains is to deprecate and remove the synchronous methods. Tracking that effort here: https://jira.omnisci.com/browse/FE-8237

**Comment by micahstubbs** [comment]
looks like https://jira.omnisci.com/browse/FE-8237 links to the closed-source issue tracker 😦
